import { type Column, type Job } from "@/types/jobs";
// Column definitions
export const columns: Column[] = [
  { id: "550e8400-e29b-41d4-a716-446655440000", name: "WISHLIST" },
  { id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa", name: "APPLIED" },
  { id: "cccccccc-cccc-cccc-cccc-cccccccccccc", name: "INTERVIEW" },
  { id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb", name: "REJECTED" },
];

// Sample jobs data
export const exampleJobs: Job[] = [
  {
    id: "task-1",
    title: "Software Engineer",
    companyName: "Google",
    columnId: "550e8400-e29b-41d4-a716-446655440000",
    companyIconUrl:
      "https://cdn.brandfetch.io/google.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Develop and maintain web applications.",
    applicationLink:
      "https://careers.google.com/jobs/results/123456-software-engineer/",
    coverLetterId: "cl-123",
    resumeId: "res-456",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-2",
    title: "UX/UI Designer",
    companyName: "Apple",
    columnId: "col-2",
    companyIconUrl: "https://cdn.brandfetch.io/TSLA?c=1idy7WQ5YtpRvbd1DQy",
    description: "Develop and maintain web applications.",
    applicationLink:
      "https://careers.google.com/jobs/results/123456-software-engineer/",
    coverLetterId: "cl-123",
    resumeId: "res-456",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-20",
    title: "Platform Engineer",
    companyName: "Shopify",
    columnId: "550e8400-e29b-41d4-a716-446655440000",
    companyIconUrl:
      "https://cdn.brandfetch.io/shopify.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Develop and maintain web applications.",
    applicationLink:
      "https://careers.google.com/jobs/results/123456-software-engineer/",
    coverLetterId: "cl-123",
    resumeId: "res-456",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-3",
    title: "Data Scientist",
    companyName: "Microsoft",
    columnId: "col-2",
    companyIconUrl:
      "https://cdn.brandfetch.io/microsoft.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Analyze large datasets and build machine learning models.",
    applicationLink: "https://careers.microsoft.com/jobs/12345",
    coverLetterId: "cl-124",
    resumeId: "res-457",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-4",
    title: "Full Stack Developer",
    companyName: "Amazon",
    columnId: "col-3",
    companyIconUrl:
      "https://cdn.brandfetch.io/amazon.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Build scalable web applications using modern technologies.",
    applicationLink: "https://www.amazon.jobs/en/jobs/12345",
    coverLetterId: "cl-125",
    resumeId: "res-458",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-5",
    title: "DevOps Engineer",
    companyName: "Netflix",
    columnId: "col-4",
    companyIconUrl:
      "https://cdn.brandfetch.io/netflix.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Build and maintain CI/CD pipelines and cloud infrastructure.",
    applicationLink: "https://jobs.netflix.com/jobs/12345",
    coverLetterId: "cl-126",
    resumeId: "res-459",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-6",
    title: "Product Manager",
    companyName: "Facebook",
    columnId: "550e8400-e29b-41d4-a716-446655440000",
    companyIconUrl: "https://cdn.brandfetch.io/meta.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Define product vision and work with engineering teams.",
    applicationLink: "https://www.metacareers.com/jobs/12345",
    coverLetterId: "cl-127",
    resumeId: "res-460",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-7",
    title: "Mobile Developer",
    companyName: "Airbnb",
    columnId: "col-2",
    companyIconUrl:
      "https://cdn.brandfetch.io/airbnb.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Develop native iOS and Android applications.",
    applicationLink: "https://careers.airbnb.com/positions/12345",
    coverLetterId: "cl-128",
    resumeId: "res-461",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-8",
    title: "Frontend Engineer",
    companyName: "Twitter",
    columnId: "col-3",
    companyIconUrl:
      "https://cdn.brandfetch.io/twitter.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Build responsive and interactive user interfaces.",
    applicationLink: "https://careers.twitter.com/jobs/12345",
    coverLetterId: "cl-129",
    resumeId: "res-462",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-9",
    title: "Machine Learning Engineer",
    companyName: "Uber",
    columnId: "col-2",
    companyIconUrl: "https://cdn.brandfetch.io/uber.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Implement and deploy machine learning models at scale.",
    applicationLink: "https://www.uber.com/careers/12345",
    coverLetterId: "cl-130",
    resumeId: "res-463",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-10",
    title: "QA Engineer",
    companyName: "LinkedIn",
    columnId: "550e8400-e29b-41d4-a716-446655440000",
    companyIconUrl:
      "https://cdn.brandfetch.io/linkedin.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Design and implement automated testing frameworks.",
    applicationLink: "https://www.linkedin.com/jobs/12345",
    coverLetterId: "cl-131",
    resumeId: "res-464",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-11",
    title: "Backend Engineer",
    companyName: "Slack",
    columnId: "col-2",
    companyIconUrl: "https://cdn.brandfetch.io/slack.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Design and implement scalable APIs and microservices.",
    applicationLink: "https://slack.com/careers/12345",
    coverLetterId: "cl-132",
    resumeId: "res-465",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-12",
    title: "Security Engineer",
    companyName: "Dropbox",
    columnId: "col-3",
    companyIconUrl:
      "https://cdn.brandfetch.io/dropbox.com?c=1idy7WQ5YtpRvbd1DQy",
    description:
      "Implement security best practices and conduct security reviews.",
    applicationLink: "https://www.dropbox.com/jobs/12345",
    coverLetterId: "cl-133",
    resumeId: "res-466",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // 10 new jobs added below
  {
    id: "task-13",
    title: "Cloud Architect",
    companyName: "Salesforce",
    columnId: "col-4",
    companyIconUrl:
      "https://cdn.brandfetch.io/salesforce.com?c=1idy7WQ5YtpRvbd1DQy",
    description:
      "Design and implement cloud-based solutions and infrastructure.",
    applicationLink:
      "https://salesforce.wd1.myworkdayjobs.com/External_Career_Site/job/12345",
    coverLetterId: "cl-134",
    resumeId: "res-467",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-14",
    title: "Blockchain Developer",
    companyName: "Coinbase",
    columnId: "550e8400-e29b-41d4-a716-446655440000",
    companyIconUrl:
      "https://cdn.brandfetch.io/coinbase.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Build decentralized applications and smart contracts.",
    applicationLink: "https://www.coinbase.com/careers/positions/12345",
    coverLetterId: "cl-135",
    resumeId: "res-468",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-15",
    title: "AR/VR Engineer",
    companyName: "Unity",
    columnId: "col-2",
    companyIconUrl: "https://cdn.brandfetch.io/unity.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Develop immersive augmented and virtual reality experiences.",
    applicationLink: "https://careers.unity.com/position/12345",
    coverLetterId: "cl-136",
    resumeId: "res-469",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-16",
    title: "Technical Program Manager",
    companyName: "Adobe",
    columnId: "col-3",
    companyIconUrl: "https://cdn.brandfetch.io/adobe.com?c=1idy7WQ5YtpRvbd1DQy",
    description:
      "Coordinate cross-functional teams and manage technical projects.",
    applicationLink: "https://www.adobe.com/careers/12345",
    coverLetterId: "cl-137",
    resumeId: "res-470",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-17",
    title: "Database Administrator",
    companyName: "Oracle",
    columnId: "col-2",
    companyIconUrl:
      "https://cdn.brandfetch.io/oracle.com?c=1idy7WQ5YtpRvbd1DQy",
    description:
      "Manage and optimize database systems and ensure data integrity.",
    applicationLink: "https://oracle.taleo.net/careersection/12345",
    coverLetterId: "cl-138",
    resumeId: "res-471",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-18",
    title: "Embedded Systems Engineer",
    companyName: "Tesla",
    columnId: "550e8400-e29b-41d4-a716-446655440000",
    companyIconUrl: "https://cdn.brandfetch.io/tesla.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Develop firmware for automotive systems and IoT devices.",
    applicationLink: "https://www.tesla.com/careers/search/job/12345",
    coverLetterId: "cl-139",
    resumeId: "res-472",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-19",
    title: "Quantum Computing Researcher",
    companyName: "IBM",
    columnId: "col-3",
    companyIconUrl: "https://cdn.brandfetch.io/ibm.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Research and develop quantum algorithms and applications.",
    applicationLink: "https://careers.ibm.com/job/12345",
    coverLetterId: "cl-140",
    resumeId: "res-473",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-21",
    title: "Game Developer",
    companyName: "Electronic Arts",
    columnId: "col-4",
    companyIconUrl: "https://cdn.brandfetch.io/ea.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Create engaging gameplay experiences and game mechanics.",
    applicationLink: "https://www.ea.com/careers/careers-overview/12345",
    coverLetterId: "cl-141",
    resumeId: "res-474",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-22",
    title: "Robotics Engineer",
    companyName: "Boston Dynamics",
    columnId: "550e8400-e29b-41d4-a716-446655440000",
    companyIconUrl:
      "https://cdn.brandfetch.io/bostondynamics.com?c=1idy7WQ5YtpRvbd1DQy",
    description: "Design and program autonomous robotic systems.",
    applicationLink: "https://www.bostondynamics.com/careers/12345",
    coverLetterId: "cl-142",
    resumeId: "res-475",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-23",
    title: "Growth Hacker",
    companyName: "Spotify",
    columnId: "col-2",
    companyIconUrl:
      "https://cdn.brandfetch.io/spotify.com?c=1idy7WQ5YtpRvbd1DQy",
    description:
      "Develop strategies to increase user acquisition and retention.",
    applicationLink: "https://www.lifeatspotify.com/jobs/12345",
    coverLetterId: "cl-143",
    resumeId: "res-476",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
